# Generated by Django 5.2.6 on 2025-09-19 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaryuser",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="temporaryuser",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FailedLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email", "timestamp"],
                        name="authenticat_email_48f25e_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="authenticat_ip_addr_8f98af_idx",
                    ),
                ],
            },
        ),
    ]
