# Generated by Django 5.2.6 on 2025-09-23 17:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_announcement_usernotification_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaryuser",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="temporaryuser",
            name="two_factor_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="temporaryuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("administrador", "Administrador"),
                    ("residente", "Residente"),
                    ("guardia", "Guardia de Seguridad"),
                    ("tecnico", "Personal de Mantenimiento"),
                    ("visitante", "Visitante"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PhoneVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("verification_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.temporaryuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TwoFactorCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.temporaryuser",
                    ),
                ),
            ],
        ),
    ]
